In [8]:
import pandas as pd
import matplotlib.pyplot as plt
# Dependencies
import requests
from pprint import pprint
import numpy as np
import gmaps
import json
import os
from scipy.stats import linregress
from datetime import datetime
import time

# Google developer API key
#from config import g_key

In [9]:
deforest_df = pd.read_csv("csv_files/deforestation_by_brazil_state.csv")

deforest_df=deforest_df.rename(columns={"Acre": "AC", "AMAPÁ":"AP","AMAZONAS":"AM","MARANHÃO":"MA","MATO GROSSO":"MT","PARÁ":"PA", "RONDÔNIA":"RO", "RORAIMA":"RR","TOCANTINS":"TO"})


deforest_df.set_index("Years", inplace =True)

deforest_df.to_csv("csv_files/clean_defostation_data.csv")

deforest_df

       ACRE   AP    AM    MA     MT    PA    RO   RR   TO  Grand Total
Years
1988    620   60   151   245    514   699   234  290  165         2978
1989    540  130   118   142    596   575   143  630  730         3604
1990    550  250   520    11    402   489   167  150  580         3119
1991    380  410   980   670    284   378   111  420  440         4073
1992    400   36   799  1135   4674  3787  2265  281  409        13786
1993    482    0   370   372    622  4284  2595  240  333         9298
1994    482    0   370   372    622  4284  2595  240  333         9298
1995   1208    9  2114  1745  10391  7845   473  220  797        24802
1996    433    0  1023  1061   6543  6135  2432  214  320        18161
1997    358   18   589   409   5271  4139  1986  184  273        13227
1998    536   30   670  1012   6466  5829  2041  223  576        17383
1999    441    0   720   123   6963  5111  2358  220  216        16152
2000    547    0   612  1065   6369  6671  2465  253  244        18226
2001    419    7   634   958   7703  5237  2673  345  189        18165
2002    883    0   885  1085   7892   751  3099   84  212        14891
2003   1078   25  1558   993  10405  7145  3597  439  156        25396
2004    728   46  1232   755  11814   887  3858  311  158        19789
2005    592   33   775   922   7145  5899  3244  133  271        19014
2006    398   30   788   674   4333  5659  2049  231  124        14286
2007    184   39   610   631   2678  5526  1611  309   63        11651
2008    254  100   604  1271   3258  5607  1136  574  107        12911
2009    167   70   405   828   1049  4281   482  121   61         7464
2010    259   53   595   712    871   377   435  256   49         3607
2011    280   66   502   396    112  3008   865  141   40         5410
2012    305   27   523   269    757  1741   773  124   52         4571
2013    221   23   583   403   1139  2346   932  170   74         5891
2014    309   31   500   257   1075  1887   684  219   50         5012
2015    264   25   712   209   1601  2153   103  156   57         5280
2016    372   17  1129   258   1489  2992  1376  202   58         7893
2017    257   24  1001   265   1561  2433  1243  132   31         6947
2018    444   24  1045   253    149  2744  1316  195   25         6195
2019    682   32  1434   237   1702  4172  1257  590   23        10129
2020    652   81  1521   290   1767  5192  1259  300   26        11088

In [10]:
#ax1=deforest_df.pivot(index="Years", values=['AP',"AM","MA","MT","PA","RO","RR","TO"])
#ax1.plot()

In [11]:
#figure, axes =plt.subplots(1,2)
#deforest_df["MATO GROSSO"].plot(ax=axes[0])
#deforest_df["ACRE"].plot(ax=axes[1])